version: '3'
# Replace network name with the fabric test-network name
services:
  redis:
    image: 'redis'
    command:
      ['--maxmemory-policy', 'noeviction', '--requirepass', '${REDIS_PASSWORD}']
    ports:
      - 6379:6379
    networks:
      - voting_system

  nodeapp:
    image: 'docker.io/mvortizr/ch1_api:v1.0'
    command: ['start:dotenv']
    ports:
      - 3000:3000
    env_file:
      - ./.env
    environment:
      - REDIS_PASSWORD
    networks:
      - voting_system

networks:
  voting_system:
    external: true
