version: '3'
# Replace network name with the fabric test-network name
services:
  redis:
    image: 'redis'
    command:
      ['--maxmemory-policy', 'noeviction', '--requirepass', '${REDIS_PASSWORD}']
    ports:
      - 6379:6379
    networks:
      - voting-system-bchain-api

  nodeapp:
    image: 'ghcr.io/hyperledger/fabric-rest-sample:latest'
    command: ['start:dotenv']
    ports:
      - 3000:3000
    env_file:
      - ./.env
    environment:
      - REDIS_PASSWORD
    networks:
      - voting-system-bchain-api

networks:
  voting-system-bchain-api:
    external: true
