# couchdb-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim # Solicitud de un volumen persistente
metadata:
  name: couchdb-data-pvc # Nombre de nuestra solicitud de almacenamiento
spec:
  accessModes:
    - ReadWriteOnce # El volumen puede ser montado como lectura/escritura por un único nodo.
  resources:
    requests:
      storage: 1Gi # Solicitamos 1 Gigabyte de almacenamiento.