# couchdb-service.yaml
apiVersion: v1
kind: Service # Define cómo acceder a un conjunto de Pods
metadata:
  name: couchdb-service # Nombre del Service (este será el nombre de host para NestJS)
spec:
  selector:
    app: couchdb # Coincide con los Pods que tienen la etiqueta 'app: couchdb'
  ports:
    - protocol: TCP
      port: 5984 # El puerto del Service (accesible por otros Pods en el clúster)
      targetPort: 5984 # El puerto del contenedor al que se redirige el tráfico
  type: ClusterIP # Este tipo de Service solo es accesible desde dentro del clúster.