apiVersion: v1
data:
  password: bWljb250cmFzZW5hU2VndXJh
  username: YWRtaW4=
kind: Secret
metadata:
  creationTimestamp: "2025-06-29T14:47:08Z"
  name: couchdb-creds
  namespace: default
  resourceVersion: "929649"
  uid: fd62ae3c-52d1-48b4-ab6f-825e59693774
type: Opaque
