# couchdb-deployment.yaml
apiVersion: apps/v1
kind: Deployment # Define un conjunto deseado de Pods idénticos
metadata:
  name: couchdb-deployment # Nombre de nuestro Deployment
spec:
  replicas: 1 # Queremos 1 copia (Pod) de CouchDB por ahora.
  selector:
    matchLabels:
      app: my-couchdb # Esto coincide con los labels de los Pods que gestiona este Deployment
  template:
    metadata:
      labels:
        app: my-couchdb # Etiquetas para identificar los Pods de CouchDB
    spec:
      containers:
        - name: my-couchdb # Nombre del contenedor
          image: couchdb:latest # La imagen de Docker a usar (se descargará de Docker Hub)
          ports:
            - containerPort: 5984 # El puerto en el que CouchDB escucha dentro del contenedor
          env: # Variables de entorno para el contenedor
            - name: COUCHDB_USER
              valueFrom: # Obtener el valor de un Secret
                secretKeyRef:
                  name: couchdb-creds # Nombre del Secret que creamos
                  key: username # La clave dentro del Secret (username)
            - name: COUCHDB_PASSWORD
              valueFrom: # Obtener el valor de un Secret
                secretKeyRef:
                  name: couchdb-creds
                  key: password # La clave dentro del Secret (password)
          volumeMounts: # Cómo montar el almacenamiento persistente
            - name: couchdb-persistent-storage # Nombre de la definición del volumen (abajo)
              mountPath: /opt/couchdb/data # Ruta dentro del contenedor donde CouchDB almacena sus datos
      volumes: # Definición de los volúmenes para los Pods
        - name: couchdb-persistent-storage
          persistentVolumeClaim:
            claimName: couchdb-data-pvc # Referencia a nuestra solicitud de almacenamiento