# nestjs-api-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nestjs-api-service # Nombre del Service de tu API
spec:
  selector:
    app: nestjs-api # Coincide con los Pods de tu API
  ports:
    - protocol: TCP
      port: 3000 # Puerto del Service
      targetPort: 3000 # Puerto del contenedor
  type: NodePort # Tipo de Service: expone un puerto en cada nodo del clúster (para acceso externo)