import { Controller, Get, Res, UseGuards, Post, Body } from '@nestjs/common';

import { Response } from 'express';
import { VoteService } from './vote.service';
import { ApiKeyGuard } from 'src/middleware/auth.middleware';
import { FabricService } from '../../fabric/fabric.service';
import { ApiHeader, ApiOperation} from '@nestjs/swagger';
import { VoteInfoDTO } from './dtos/dto_vote_info';
import { v4 as uuidv4 } from 'uuid';

// DTOS
// cambiar a vote registry 


@ApiHeader({
  name: 'auth',
  description: 'Api key token',
  required: true,
})
@Controller('vote')
@UseGuards(ApiKeyGuard)
export class VoteController {
  
  constructor(
    private readonly voteService: VoteService, 
    private readonly fabricService: FabricService
  ) {
    this.fabricService.connect();
  }



  @Post('/dummy_vote_register')
  @ApiOperation({ summary: "Create a dummy of vote register just to tests counting " })
  async dummyVoteRegister(@Res() res: Response): Promise<object> {
    const chaincode = process.env.CHAINCODE_NAME!.toString()
    const functionName = "VoteRegistryContract:dummyVoteRegister"
    const internalRegistryUID: string = uuidv4();
    const electorIntID: string = uuidv4(); // autogenerated
    const electorExtID: string = uuidv4(); // autogenerated

    

    const result = await this.fabricService.submitTransaction(
      chaincode,
      functionName,
      internalRegistryUID,
      electorIntID,
      electorExtID
    )

    let parsedResults = new TextDecoder().decode(result);
    let finalResult  = JSON.parse(parsedResults);

    if (!finalResult.success) {
      return res.status(400).json({ statusCode: 400, ...finalResult });
    }

    // return if not problems
    return res.status(201).json({ statusCode: 201, message: 'vote registry saved correctly' });
  }

  @Post('/precount')
  @ApiOperation({ summary: 'Trigger vote precount (every 500 entries)' })
  async makePrecount(@Res() res: Response): Promise<object> {
    const chaincode = process.env.CHAINCODE_NAME!.toString();
    const functionName = 'VoteRegistryContract:makePrecount';

    const result = await this.fabricService.submitTransaction(chaincode, functionName, '{}');

    const parsedResults = new TextDecoder().decode(result);
    const finalResult = JSON.parse(parsedResults);

    if (!finalResult.success) {
      return res.status(400).json({ statusCode: 400, ...finalResult });
    }

    return res.status(200).json({ statusCode: 200, ...finalResult });
  }

  @Post('/final_count')
  @ApiOperation({ summary: 'Aggregate all precounts into a final result' })
    async finalCount(@Res() res: Response): Promise<object> {
    const chaincode = process.env.CHAINCODE_NAME!.toString();
    const functionName = 'VoteRegistryContract:finalCount';

    const result = await this.fabricService.submitTransaction(chaincode, functionName);

    const parsedResults = new TextDecoder().decode(result);
    const finalResult = JSON.parse(parsedResults);

    if (!finalResult.success) {
      return res.status(400).json({ statusCode: 400, ...finalResult });
    }

    return res.status(200).json({ statusCode: 200, ...finalResult });
  }

  @Get('/readAllAssets') /// DEBUG ONLY
  @ApiOperation({ summary: '(DEBUG ONLY) Dumps every data inside the channel unordered' })
  async readAllAssets( @Res() res: Response): Promise<object> {
    // async submitTransaction(chaincodeName: string, functionName: string, ...args: string[])
    const chaincode = process.env.CHAINCODE_NAME!.toString()
    const functionName = "readEntireElectoralChannel"
    const result = await this.fabricService.evaluateTransaction(chaincode, functionName)
    return res.status(200).json({ statusCode: 200, result: result });
  }

  

  @Post('/register')
  @ApiOperation({ summary: "Lets user vote for a candidate" })
  async setVote(@Body() voteInfo: VoteInfoDTO, @Res() res: Response): Promise<object> {
    const chaincode = process.env.CHAINCODE_NAME!.toString()
    const functionName = "VoteRegistryContract:createVoteRegistry"
    const internalRegistryUID: string = uuidv4();
    const API_1_URL = process.env.API_1_URL!;
    const API_3_URL = process.env.API_3_URL!;


    //TODO esta abierta la votacion? (a api 3)


    // Llamar api #1 y revisar que es valido
    const postDataToSend = {
      electorID: voteInfo.electorID,
      postulationID: voteInfo.postulationID,
      candidateID: voteInfo.candidateID
    };
    
  
    const response = await this.voteService.postData(`${API_1_URL}/elector/validatePreVoteElector`,postDataToSend)
    

    if (!response.success) {
      return res.status(400).json({ statusCode: 400, ...response });
    }
  
    let electorIntID = response.electorIntID
    let positionExtID = response.positionExtID
    let positionIntID = response.positionIntID
    let multiplier = response.multiplier

    ////////// Escribir en el cuaderno de votacion ////////////
    const result = await this.fabricService.submitTransaction(
      chaincode,
      functionName,
      internalRegistryUID,
      electorIntID,
      voteInfo.electorID,   
      positionIntID,
      positionExtID
    )

    
    let parsedResults = new TextDecoder().decode(result);
    let finalResult  = JSON.parse(parsedResults);

    if (!finalResult.success) {
      return res.status(400).json({ statusCode: 400, ...finalResult });
    } 

    //////////// guardar el registro del voto (API #3 llamada) /////////
    const postDataToSendApi3 = {
      positionID: positionIntID,
      positionExtID: positionExtID,
      postulationID: response.postulacionIntID,
      postulationExtID:voteInfo.postulationID,
      candidateID: response.candidateIntID,
      candidateExtID:voteInfo.candidateID,
      partyID: response.partyIntID,
      partyExtID: response.partyExtID,
      multiplier: multiplier
    };

    //
    const responseStoreVote = await this.voteService.postData(`${API_3_URL}/vote/register`,postDataToSendApi3)

    if (!responseStoreVote.success) {
      return res.status(400).json({ statusCode: 400, ...responseStoreVote });
    }

    // return if not problems
    return res.status(201).json({ statusCode: 201, message: 'vote saved correctly' });

  }


 
}
